[build]
  # Папка со сгенерированным Hugo-сайтом
  publish = "public"
  # Команда сборки Hugo
  command = "hugo --gc --minify"

[build.environment]
  # Версия Node.js (для PostCSS и плагинов)
  NODE_VERSION = "22"
  # Исправляем ошибку с lockfile при pnpm install
  PNPM_FLAGS = "--no-frozen-lockfile"
  NPM_FLAGS = "--no-frozen-lockfile"
  # Версия Hugo Extended
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"

# === Контексты деплоя ===
[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_ENV = "development"

# === Настройки ветки для автодеплоя ===
[build.branch]
  # Автодеплой только из main
  main = { publish = "public", command = "hugo --gc --minify" }


