[build]
  # Директория, куда Hugo собирает сайт
  publish = "public"
  # Команда сборки
  command = "hugo --gc --minify"

[build.environment]
  # Версия Node.js (подходит для Hugo + PostCSS)
  NODE_VERSION = "22"
  # Отключаем frozen-lockfile для pnpm
  PNPM_FLAGS = "--no-frozen-lockfile"
  NPM_FLAGS = "--no-frozen-lockfile"
  # Версия Hugo (Extended)
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "development"

[context.branch-deploy.environment]
  HUGO_ENV = "development"
